server:
  port: 7002
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      mvc:
        routes[0]:
          id: customer-service
          predicates[0]: Path=/customer-service/api/v1/customers/**
          predicates[1]: Path=/customer-service/api/v1/addresses/**
          predicates[2]: Path=/customer-service/api/v1/individual-customers/**
          predicates[3]: Path=/customer-service/api/v1/cities/**
          uri: lb://customerService
        routes[1]:
          id: discoveryserver
          predicates[0]: Path=/eureka/web
          filters[0]: SetPath=/
          uri: http://localhost:7000
          routes[2]:
            id: identity-service
            predicates[0]: Path=/identity-service/api/v1/auth/**
            filters[0]: SetPath=/
            uri: lb://identityService
          routes[3]:
            id: search-service
            predicates[0]: Path=/search-service/api/v1/customers/**
            uri: lb://searchService
          routes[4]:
            id: account-service
            predicates[0]: Path=/account-service/api/v1/accounts/**
            predicates[1]: Path=/account-service/api/v1/addresses/**
            predicates[2]: Path=/account-service/api/v1/account-types/**
            uri: lb://accountService
          routes[5]:
            id: catalog-service
            predicates[0]: Path=/catalog-service/api/v1/products/**
            uri: lb://catalogService