server:
  port: 7002
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      mvc:
        routes[0]:
          id: customer-service
          uri: lb://customerService
        routes[1]:
          id: discoveryserver
          predicates[0]: Path=/eureka/web
          filters[0]: SetPath=/
          uri: http://localhost:7000
          routes[2]:
            id: identity-service
            filters[0]: SetPath=/
            uri: lb://identityService
          routes[3]:
            id: search-service
            uri: lb://searchService
          routes[4]:
            id: account-service
            uri: lb://accountService
          routes[5]:
            id: catalog-service
            uri: lb://catalogService
          routes[6]:
            id: basket-service
            uri: lb://basketService
          routes[7]:
            id: order-service
            uri: lb://orderService